---
date: "2022-07-15"
title: Quarto
subtitle: Weave text and code and render into many outputs
tags:
- Quarto
- R
- Python
- Jupyter 
- Observable JS
- Julia
- Pdf
- HTML

editor_options: 
  markdown: 
    wrap: 72
---

Checking out [Quarto](https://quarto.org) today. It looks like a more comprehensive tool than R Markdown though it does a lot of similar things like being able to write text and include code cells (like Jupyter), but then also able to render the output into many formats (pdf, html, word, etc) using Pandoc. I guess that makes sense since it's published by the same folks behind R Markdown and R Studio:

>  Quarto is a multi-language, next-generation version of R Markdown from RStudio, and includes dozens of new features and capabilities while at the same being able to render most existing Rmd files without modification.

It's also able to handle more languages in code cells than R Markdown. It's fairly new so support isn't as widespread as it is for rmarkdown. For example, I made a resume yesterday using pagedown or blogdown (I don't remember which already), but I don't see a readily available template for creating resumes yet in Quarto though I'm sure it will be coming soon.

Installing Quarto is easy and I had it up and running under Visual Studio and R Studio in 5 mins. A helpoful quick start guide is [here](https://quarto.org/docs/get-started/).

